# Generated by Django 4.1.3 on 2022-12-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_hours', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
