# Generated by Django 4.1.3 on 2022-12-01 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sleep_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleep',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleeps', to=settings.AUTH_USER_MODEL),
        ),
    ]
