# Generated by Django 4.1.3 on 2022-12-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleep',
            name='date',
            field=models.DateField(),
        ),
    ]
