# Generated by Django 4.1.3 on 2022-12-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_sex',
            field=models.BooleanField(choices=[('M', 'Male'), ('F', 'Female')], default='Male'),
            preserve_default=False,
        ),
    ]
