# Generated by Django 4.1.3 on 2022-12-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_sex',
            field=models.BooleanField(choices=[(True, 'Male'), (False, 'Female')], null=True),
        ),
    ]
